name: Rubocop Linter

on:
  push:
    branches-ignore:
      - master


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rubocop Linter
      uses: actions/rubocop@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
