env:
  RUBY_VERSION: 3.0

name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      
      - name: Install Rubocop
        run: gem install rubocop

      - name: Check code
        run: rubocop
  
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install Rspec
        run: gem install rspec

      - name: Install Simplecov
        run: gem install simplecov
      
      - name: Run barco test
        run: rspec ./spec/barco_test.rb

      - name: Run jugador test
        run: rspec ./spec/jugador_test.rb 

      - name: Run tablero test
        run: rspec ./spec/tablero_test.rb

      - name: Run juego test
        run: rspec ./spec/juego_test.rb 